### ISSUE TITLE
[Bug] v0.9.12 fails to load

### ISSUE THREAD

**Issue by Mapleshade20** [alvinunreal/oh-my-opencode-slim#298]
After upgrading to 0.9.12, omo-slim doesn't successfully load.

I notice the plugin config of opencode is "oh-my-opencode-slim" now, no longer a static file path. I suspect there's a bug behind this.

**Comment by Mapleshade20** [comment]
Manually reverting `opencode.json` is a temporary workaround-- omo-slim loads after this.

```json
	"plugin": [
		"/private/var/folders/dj/5_y_ywys2238hbrgkw86h4gw0000gn/T/bunx-501-oh-my-opencode-slim@latest/node_modules/oh-my-opencode-slim/dist/index.js"
	],
```

**Comment by alvinunreal** [comment]
I just installed on fresh machine, can't reproduce

**Comment by whackur** [comment]
## Root Cause Analysis

The OpenCode desktop app (Electron) runs the server **in-process using Node.js**, not Bun. When the plugin is loaded via dynamic `import()`, two things fail:

1. **`import { spawn } from 'bun'`** — The `bun` module doesn't exist in Node.js, so the import fails immediately at load time, preventing the entire plugin from loading.
2. **`--target bun` build output** — Bun's bundler generates a `__require` helper that is Bun-specific. In Node.js this throws `__require is not a function`.

This is why the plugin works in CLI mode (Bun binary) but fails in the desktop app (Electron/Node.js). The error in the server log is:

```
ERROR service=plugin path=oh-my-opencode-slim error=__require is not a function failed to load plugin
```

## Fix

PR #299 replaces all Bun-specific APIs with `node:child_process` and `node:fs/promises`, which are **fully supported in both Bun and Node.js** — no performance loss, no feature loss. The build target is also changed from `--target bun` to `--target node`.

| Before (Bun-only) | After (cross-runtime) |
|---|---|
| `import { spawn } from 'bun'` | `spawn` from `node:child_process` via `crossSpawn()` utility |
| `Bun.write()` | `writeFile` from `node:fs/promises` via `crossWrite()` utility |
| `Bun.spawn()` | `crossSpawn()` |
| `bun build --target bun` | `bun build --target node` |

All 532 tests pass. Verified working in both CLI (Bun) and desktop (Electron).

See: https://github.com/alvinunreal/oh-my-opencode-slim/pull/299

**Comment by Mapleshade20** [comment]
> I just installed on fresh machine, can't reproduce

Did you install opencode with npm or bun?

**Comment by gustavocaiano** [comment]
> I just installed on fresh machine, can't reproduce

autoupdated to 0.9.12 and now isnt loading plugin

**Comment by Mapleshade20** [comment]
The failure was on my MacBook. I just tested with my ArchLinux instance, upgrading from yesterday's version to today's 0.9.12, and it turned out working. In both cases `opencode` is installed via npm and `omo-slim` via bunx. I don't know how to explain this.

**Comment by gustavocaiano** [comment]
im on mac too, not sure whats happening so if you end up finding out let me know! @Mapleshade20

**Comment by MCKLtech** [comment]
> In both cases `opencode` is installed via npm and `omo-slim` via bunx. I don't know how to explain this.

I had the same issue. I installed omo-slim with bunx and it does not appear in my OpenCode Desktop or OpenChamber any more. But when I installed via npm install oh-my-opencode-slim@latest it fixed it.
